# Generated by Django 5.2.5 on 2025-10-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0003_instituicao_turma_instituicao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='turma_empresa',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'empresa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_empresa', to='instituicoes.turma'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma_escola',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'escola'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_escola', to='instituicoes.turma'),
        ),
    ]
