# Generated by Django 5.2.5 on 2025-10-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0003_instituicao_turma_instituicao'),
        ('usuarios', '0003_frequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('atrasado', 'Atrasado'), ('fora_dia', 'Fora do dia'), ('invalido', 'Inválido')], max_length=20)),
                ('estagiario', models.ForeignKey(limit_choices_to={'cargo': 'estagiario'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.instituicao')),
            ],
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
