# Generated by Django 5.2.5 on 2025-10-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0007_alter_turma_dias_semana'),
        ('usuarios', '0006_usuario_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turma_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_gestor', to='instituicoes.turma'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.CharField(choices=[('presente', 'Presente'), ('atrasado', 'Atrasado'), ('invalido', 'Inválido')], max_length=20),
        ),
    ]
