# Generated by Django 5.2.5 on 2025-10-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_turma_gestor_alter_registro_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='turma_gestor',
        ),
    ]
