# Generated by Django 5.2.5 on 2025-10-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0009_remove_turma_tipo'),
        ('usuarios', '0008_remove_usuario_turma_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='justificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma_empresa',
            field=models.ForeignKey(blank=True, limit_choices_to={'instituicao__tipo': 'empresa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_empresa', to='instituicoes.turma'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turma_escola',
            field=models.ForeignKey(blank=True, limit_choices_to={'instituicao__tipo': 'escola'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_escola', to='instituicoes.turma'),
        ),
    ]
