# Generated by Django 5.2.5 on 2025-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_registro_justificado_alter_usuario_turma_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora_registro',
            field=models.TimeField(),
        ),
    ]
