# Generated by Django 5.2.5 on 2025-10-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0010_remove_demanda_gestor'),
        ('usuarios', '0010_alter_registro_hora_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='turma_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_registro', to='instituicoes.turma'),
        ),
    ]
