# Generated by Django 5.2.5 on 2025-10-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_registro_turma_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='turma_empresa',
            new_name='turma',
        ),
    ]
