# Generated by Django 5.2.5 on 2025-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_turma_empresa_registro_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
