# Generated by Django 5.2.5 on 2025-10-04 11:51

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', multiselectfield.db.fields.MultiSelectField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('escola', 'Escola'), ('empresa', 'Empresa')], max_length=10)),
                ('data_inicio_ano', models.DateField()),
                ('data_fim_ano', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('vezes_por_semana', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
