# Generated by Django 5.2.5 on 2025-10-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='vezes_por_semana',
        ),
    ]
