# Generated by Django 5.2.5 on 2025-10-04 12:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0003_instituicao_turma_instituicao'),
        ('usuarios', '0005_alter_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField(blank=True, default=datetime.date.today)),
                ('entrega', models.DateField(blank=True, null=True)),
                ('gestor', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'gestor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_que_ele_gera', to='instituicoes.turma')),
            ],
        ),
    ]
