# Generated by Django 5.2.5 on 2025-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0004_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('escola', 'Escola'), ('empresa', 'Empresa')], max_length=10),
        ),
    ]
