# Generated by Django 5.2.5 on 2025-10-04 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0005_instituicao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituicao_disp', to='instituicoes.instituicao')),
            ],
        ),
    ]
