# Generated by Django 5.2.5 on 2025-10-04 14:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0006_dispositvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dias_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=50),
        ),
    ]
