# Generated by Django 5.2.5 on 2025-10-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0007_alter_turma_dias_semana'),
        ('usuarios', '0008_remove_usuario_turma_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='gestor',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'gestor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
