# Generated by Django 5.2.5 on 2025-10-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0009_remove_turma_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='gestor',
        ),
    ]
