# Generated by Django 5.2.5 on 2025-10-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0010_remove_demanda_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], max_length=10),
        ),
    ]
