# Generated by Django 5.2.5 on 2025-10-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0011_demanda_status'),
        ('usuarios', '0012_rename_turma_empresa_registro_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositvo',
            name='ultimo_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='gestor',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'gestor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='instituicoes.instituicao'),
        ),
    ]
