# Generated by Django 5.2.5 on 2025-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0012_dispositvo_ultimo_ping_alter_turma_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositvo',
            name='ultimo_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
